version: '2'
services:
  web:
    image: httpd:2.2.32
    ports:
      - "9990:8080"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

